### PR TITLE
WP-r51586: Rename the readonly() function to `wp_readonly()`

### LINKED ISSUE #775: PHP 8.1: syntax error due to new 'readonly' property
As reported in https://core.trac.wordpress.org/ticket/53858

## Description
New 'readonly' property modifier is introduced to PHP 8.1 after commit [6780aaa5](https://github.com/php/php-src/commit/6780aaa5). That means, 'readonly' becomes one keyword.

However, there is a function named 'readonly' in wordpress, which would lead to a syntax error, as shown in the following error message:

```
Parse error: syntax error, unexpected token "readonly", expecting "(" in /var/www/html/php-bench/wordpress/wp-includes/general-template.php on line 4823
```

## Proposed Solution
A backport of [changeset 51586](https://core.trac.wordpress.org/changeset/51586)

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Backport of upstream fix for PHP8.1 reserved name.

## Motivation and context
This change ensure future compatibility with PHP8.1 and closes #775

## How has this been tested?
Upstream backport
Unit test files included in backport changes

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

File: src/wp-includes/php-compat/readonly.php [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * Conditionally declares a `readonly()` function, which was renamed
+ * to `wp_readonly()` in WordPress 5.9.0.
+ *
+ * In order to avoid PHP parser errors, this function was extracted
+ * to this separate file and is only included conditionally on PHP 8.1.
+ *
+ * Including this file on PHP >= 8.1 results in a fatal error.
+ *
+ * @package WordPress
+ * @since 5.9.0
```
Comment (bahiirwa) [inline src/wp-includes/php-compat/readonly.php:12]: Shouldn't this have "wp-5.9.0"?

Comment (mattyrob) [reply src/wp-includes/php-compat/readonly.php]: It should - and in some other placed in their file too - updated PR to follow.

**Review by bahiirwa — APPROVED** [review]
