### PR TITLE
Fix #194 and #198

### LINKED ISSUE #194: Broken gravatar and reference to wapuu in example comment
When doing a fresh install, a single test comment is added to the system by *A ClassicPress Commenter*. In WP, this example user's email address resolves to a valid Gravatar, but in CP it does not. If Gravatars will remain in CP, then the example should have an email that is attached to an actual working Gravatar account. Also, the term "wapuu" should be nixed – that's a WordPress thing.

## Expected behavior
Working avatar. No reference to wapuu.

## Current behavior
Broken avatar. Reference to wapuu.

## Possible solution
Fix avatar. Remove reference to wapuu.

## Steps to reproduce (for bugs)
Install CP.

### PR DESCRIPTION
**Pull request by johnalarcon**
For issue #194, #198. This PR corrects the default email of the example commenter installed with the system, and updates support URLs.

## Description
Changed email from wapuu@classicpress.example to social@classicpress.net. Updated source URLs to reflect current support channels.

## Motivation and context
Email address was invalid; support URLs invalid.

## How has this been tested?
Locally. Manually updated database with new address to see that the new avatar worked correctly.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/wp-admin/includes/class-wp-automatic-updater.php [hunk 1]
```diff
@@ -832,8 +832,8 @@ protected function send_debug_email() {
 This debugging email is sent when you are using a development version of ClassicPress.
 
 If you think these failures might be due to a bug in ClassicPress, could you report it?
- * Open a thread in the support forums: https://wordpress.org/support/forum/alphabeta
- * Or, if you're comfortable writing a bug report: https://core.trac.wordpress.org/
+ * Open a thread in the support forums: https://docs.classicpress.net/faq-support/
```
Comment (senlin) [inline src/wp-admin/includes/class-wp-automatic-updater.php]: Shouldn't the text also be adjusted? On that page it is not possible to open anything.

File: src/wp-admin/includes/class-wp-automatic-updater.php [hunk 2]
```diff
@@ -832,8 +832,8 @@ protected function send_debug_email() {
...
+ * Or, if you're comfortable writing a bug report: https://docs.classicpress.net/faq-support/
```
Comment (senlin) [inline src/wp-admin/includes/class-wp-automatic-updater.php]: And then here either change the link (to Github issues) or the text (if changing the text I think it would be better to make 1 sentence from the two of them?

**Comment by Mte90** [comment]
wondering if we can include https://github.com/ClassicPress/ClassicPress/issues/184 in that list so we can start work on localize.

File: src/wp-admin/includes/class-wp-automatic-updater.php (hunk 2 above)
Comment (johnalarcon) [reply src/wp-admin/includes/class-wp-automatic-updater.php]: Updated according to https://github.com/ClassicPress/ClassicPress/issues/198#issuecomment-435225554 . Happy to change it, if needed.

File: src/wp-admin/includes/class-wp-automatic-updater.php (hunk 1 above)
Comment (johnalarcon) [reply src/wp-admin/includes/class-wp-automatic-updater.php]: Updated according to https://github.com/ClassicPress/ClassicPress/issues/198#issuecomment-435225554 . Happy to change it, if needed.

**Comment by nylen** [comment]
@Mte90 #184 should be addressed in a separate PR.  I can do it in a few minutes.

File: src/wp-admin/includes/class-wp-automatic-updater.php (hunk 2 above)
Comment (nylen) [reply src/wp-admin/includes/class-wp-automatic-updater.php]: We don't have support forums yet, so this doesn't really make sense.

It also shouldn't be the same link twice.  Per https://github.com/ClassicPress/ClassicPress/issues/198#issuecomment-435225554 you can use https://docs.classicpress.net/testing-classicpress/#reporting-bugs for the link to report bugs.

**Comment by johnalarcon** [comment]
I've made the suggested text changes with the exception of the ../wp-admin/maint/repair.php file... The text reads,

> Some database problems could not be repaired. Please copy-and-paste the following list of errors to the <a href="%s">ClassicPress support forums</a> to get additional assistance. 

The question is: remove the language about copy/paste, or link to Slack where a copy/paste is possible, or something else?

**Comment by nylen** [comment]
Yep, I think the best thing for now is to link people to Slack.

**Comment by nylen** [comment]
@johnalarcon you can use this semi-secret page as a link to slack:  http://www.classicpress.net/join-slack/

This is better than linking directly to the Slack invite because if we ever need to change this in the future, we can do something fairly reasonable without releasing a new version of ClassicPress.

**Comment by johnalarcon** [comment]
That's the link I used... noting, though, that a better option would be to deep-link straight to the specific channel; commented same on the update. That should wrap this up.

**Comment by nylen** [comment]
Just linking to the channel is not enough, because people who don't have an account see this screen with no ability to register:

2018-11-02t19 35 38-05 00

Here is more complete wording that we've used elsewhere to do the same thing:

https://github.com/ClassicPress/ClassicPress/blob/3febb8a51cd31cc8a60d96fc2d4012d7dbbeea84/src/wp-admin/includes/dashboard.php#L1571-L1579

Anyway I agree that this is good to go as-is.

**Comment by johnalarcon** [comment]
Good point. Thanks for the additional reference.
