### PR TITLE
Fix: prompt to update core for incompatible plugins and themes

### LINKED ISSUE #1441: 🐞 Users being prompted to update core for incompatible plugins and themes.
### Expected behavior

Plugins and themes which are assumed to be incompatible with CP, due to the `Requires at least:` tag being higher than WP 6.2 cannot be installed or activated to prevent (fatal) errors in case or undefined or deprecated functions.
Users who are already running the latest version of CP should not be prompted the update CP core.

### Current behavior

If a plugin or theme is assumed to be incompatible with the installed CP version, installing and/or activating it is being prevented and the user is shown an error, such as: _"This plugin does not work with your version of ClassicPress. Please update ClassicPress."_

This error is compiled in two steps:
1. Either the plugin header or the theme's `style.css` or the remote `readme` file states that a higher version that WP 6.2 is required using the `Requires at least` tag.
2. The core code checks `current_user_can( 'update_core' )` to wether or not add the "Update ClassicPress" part, indicating that there is a newer version available.

That second part is in all likelihood confusing to users who are already running the most recent version of CP.

**Installed theme:**
Installed Theme

**Installed plugin:**
Installed Plugin

**New plugin:**
Incompatible

### Possible solution

WP core assumes there must be a newer version available, because plugins and themes do not require a WP version higher than the current release. But since CP 2.0.0 is a fork of WP 6.2.3 an additional check to determine if there is indeed a newer version of CP available is needed. The `find_core_update` function could be used for this, because it returns `FALSE` if there is no core update available.

**Files affected:**
- `wp-admin/themes.php`
- `wp-admin/theme-install.php`
- `wp-admin/includes/theme.php`
-  `wp-admin/includes/class-wp-plugin-install-list-table.php`
- `wp-admin/includes/class-wp-plugins-list-table.php`

Each of these files would then be updated with something like this:
```
global $cp_version;

$locale      = get_locale();
$core_update = find_core_update( $cp_version, $locale );

if ( ! $compatible_php || ! $compatible_wp ) {
  ...

    if ( current_user_can( 'update_core' ) && $core_update ) {
       printf(
         /* translators: %s: URL to ClassicPress Updates screen. */
         ' ' . __( '<a href="%s">Please update ClassicPress</a>.' ),
         self_admin_url( 'update-core.php' )
       );
    }
  ...
}

```

### Steps to reproduce bug

1. Make sure the latest version of CP is installed.
2. Search for a plugin in `Plugins > Add new`

### Context

_No response_

### ClassicPress version

2.0.0+dev

### PHP version

8.1

### Can you help?

Yes, I will submit a PR

### PR DESCRIPTION
**Pull request by xxsimoxx**
See #1441 .
Closes #1441 

## Description
Plugin and themes that contains `Requires at least` are checked against `$wp_version`.
At now that is `6.2.5`, but users running the latest version of ClassicPress are anyway prompted to update.

## How has this been tested?
Local testing.

### After
image

image

## Types of changes
- Bug fix

### CODE REVIEW

File: src/wp-admin/includes/theme.php [hunk 1]
```diff
@@ -966,10 +985,10 @@ function customize_themes_print_templates() {
 							<# } else if ( ! data.compatibleWP ) { #>
 								<?php
 								_e( 'This theme does not work with your version of ClassicPress.' );
-								if ( current_user_can( 'update_core' ) ) {
+								if ( current_user_can( 'update_core' ) && $cp_needs_update ) {
 									printf(
 										/* translators: %s: URL to WordPress Updates screen. */
-										' ' . __( '<a href="%s">Please update ClassicPress</a>.' ),
+										' ' . __( '<a href="%s">Please cd .Press</a>.' ),
```
Comment (mattyrob) [inline src/wp-admin/includes/theme.php:991]: This change doesn't look like it's intentional.

**Review by mattyrob — CHANGES_REQUESTED** [review]

File: src/wp-admin/includes/theme.php (hunk 1 above)
Comment (xxsimoxx) [reply src/wp-admin/includes/theme.php:991]: Seems like I was changing directory...

**Review by mattyrob — APPROVED** [review]
